
INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_TYPE
(`ID`,
`DESCRIPTION`,
`NAME`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Letters from A to F.',
'Letters'
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Article',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Article',
100
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Blog',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Blog',
200
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Gossip',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Gossip',
300
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'News',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'News',
400
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Picture',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Picture',
500
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Product',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Product',
600
);
INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Quote',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Quote',
700
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO WEB_ITEM_TYPE
(`ID`,
`DESCRIPTION`,
`FEEDBACK_TYPE_ID`,
`NAME`,
`POSITION`)
VALUES
(
(SELECT LAST_INSERT_ID()),
'Video',
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
'Video',
800
);


INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_OPTION
(`ID`,
`ICON_PATH`,
`NAME`,
`VALUE`,
`FEEDBACK_TYPE_ID`,
`POSITION`)
VALUES
(
(SELECT MAX(id) FROM _DATA_ENTITY),
'pics/feedback_options/a.png',
'Letter A',
1,
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
1
);


INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_OPTION
(`ID`,
`ICON_PATH`,
`NAME`,
`VALUE`,
`FEEDBACK_TYPE_ID`,
`POSITION`)
VALUES
(
(SELECT MAX(id) FROM _DATA_ENTITY),
'pics/feedback_options/b.png',
'Letter B',
1,
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
2
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_OPTION
(`ID`,
`ICON_PATH`,
`NAME`,
`VALUE`,
`FEEDBACK_TYPE_ID`,
`POSITION`
)
VALUES
(
(SELECT MAX(id) FROM _DATA_ENTITY),
'pics/feedback_options/c.png',
'Letter C',
1,
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
3
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_OPTION
(`ID`,
`ICON_PATH`,
`NAME`,
`VALUE`,
`FEEDBACK_TYPE_ID`,
`POSITION`)
VALUES
(
(SELECT MAX(id) FROM _DATA_ENTITY),
'pics/feedback_options/d.png',
'Letter D',
1,
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
4
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_OPTION
(`ID`,
`ICON_PATH`,
`NAME`,
`VALUE`,
`FEEDBACK_TYPE_ID`,
`POSITION`)
VALUES
(
(SELECT MAX(id) FROM _DATA_ENTITY),
'pics/feedback_options/e.png',
'Letter E',
1,
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
5
);

INSERT INTO _DATA_ENTITY VALUES (0);

INSERT INTO FEEDBACK_OPTION
(`ID`,
`ICON_PATH`,
`NAME`,
`VALUE`,
`FEEDBACK_TYPE_ID`,
`POSITION`)
VALUES
(
(SELECT MAX(id) FROM _DATA_ENTITY),
'pics/feedback_options/f.png',
'Letter F',
1,
(SELECT ID FROM FEEDBACK_TYPE WHERE NAME = 'Letters'),
6
);