ALTER TABLE `tsosm`.`user` 
CHANGE COLUMN `E_MAIL_ADDRESS` `E_MAIL_ADDRESS` VARCHAR(100) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NULL DEFAULT NULL, 
CHANGE COLUMN `USER_NAME` `USER_NAME` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_general_ci' NOT NULL;

ALTER TABLE `tsosm`.`web_item` 
CHANGE COLUMN `TEXT` `TEXT` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL , 
CHANGE COLUMN `TITLE` `TITLE` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL;


